//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class LuaFramework_TweenWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(LuaFramework.Tween), typeof(System.Object));
		L.RegFunction("SetPosition", SetPosition);
		L.RegFunction("StartMove", StartMove);
		L.RegFunction("StopMove", StopMove);
		L.RegFunction("StartParabola", StartParabola);
		L.RegFunction("StopParabola", StopParabola);
		L.RegFunction("SetScale", SetScale);
		L.RegFunction("StartScale", StartScale);
		L.RegFunction("StopScale", StopScale);
		L.RegFunction("SetUISize", SetUISize);
		L.RegFunction("StartUISize", StartUISize);
		L.RegFunction("StopUISize", StopUISize);
		L.RegFunction("SetAlpha", SetAlpha);
		L.RegFunction("StartAlpha", StartAlpha);
		L.RegFunction("StopAlpha", StopAlpha);
		L.RegFunction("StartShake", StartShake);
		L.RegFunction("StopShake", StopShake);
		L.RegFunction("StartSwing", StartSwing);
		L.RegFunction("StopSwing", StopSwing);
		L.RegFunction("StartValue", StartValue);
		L.RegFunction("Linear", Linear);
		L.RegFunction("Ease", Ease);
		L.RegFunction("New", _CreateLuaFramework_Tween);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateLuaFramework_Tween(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				LuaFramework.Tween obj = new LuaFramework.Tween();
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: LuaFramework.Tween.New");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetPosition(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			UnityEngine.Transform arg0 = (UnityEngine.Transform)ToLua.CheckObject<UnityEngine.Transform>(L, 1);
			UnityEngine.Vector3 arg1 = ToLua.ToVector3(L, 2);
			bool arg2 = LuaDLL.luaL_checkboolean(L, 3);
			LuaFramework.Tween.SetPosition(arg0, arg1, arg2);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int StartMove(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 6)
			{
				float arg0 = (float)LuaDLL.luaL_checknumber(L, 1);
				UnityEngine.Transform arg1 = (UnityEngine.Transform)ToLua.CheckObject<UnityEngine.Transform>(L, 2);
				UnityEngine.Vector3 arg2 = ToLua.ToVector3(L, 3);
				float arg3 = (float)LuaDLL.luaL_checknumber(L, 4);
				LuaFramework.Tween.EaseType arg4 = (LuaFramework.Tween.EaseType)ToLua.CheckObject(L, 5, typeof(LuaFramework.Tween.EaseType));
				bool arg5 = LuaDLL.luaL_checkboolean(L, 6);
				LuaFramework.Tween.StartMove(arg0, arg1, arg2, arg3, arg4, arg5);
				return 0;
			}
			else if (count == 7 && TypeChecker.CheckTypes<System.Action, bool>(L, 6))
			{
				float arg0 = (float)LuaDLL.luaL_checknumber(L, 1);
				UnityEngine.Transform arg1 = (UnityEngine.Transform)ToLua.CheckObject<UnityEngine.Transform>(L, 2);
				UnityEngine.Vector3 arg2 = ToLua.ToVector3(L, 3);
				float arg3 = (float)LuaDLL.luaL_checknumber(L, 4);
				LuaFramework.Tween.EaseType arg4 = (LuaFramework.Tween.EaseType)ToLua.CheckObject(L, 5, typeof(LuaFramework.Tween.EaseType));
				System.Action arg5 = (System.Action)ToLua.ToObject(L, 6);
				bool arg6 = LuaDLL.lua_toboolean(L, 7);
				LuaFramework.Tween.StartMove(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
				return 0;
			}
			else if (count == 7 && TypeChecker.CheckTypes<LuaFramework.TweenEvent, bool>(L, 6))
			{
				float arg0 = (float)LuaDLL.luaL_checknumber(L, 1);
				UnityEngine.Transform arg1 = (UnityEngine.Transform)ToLua.CheckObject<UnityEngine.Transform>(L, 2);
				UnityEngine.Vector3 arg2 = ToLua.ToVector3(L, 3);
				float arg3 = (float)LuaDLL.luaL_checknumber(L, 4);
				LuaFramework.Tween.EaseType arg4 = (LuaFramework.Tween.EaseType)ToLua.CheckObject(L, 5, typeof(LuaFramework.Tween.EaseType));
				LuaFramework.TweenEvent arg5 = (LuaFramework.TweenEvent)ToLua.ToObject(L, 6);
				bool arg6 = LuaDLL.lua_toboolean(L, 7);
				LuaFramework.Tween.StartMove(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
				return 0;
			}
			else if (count == 11)
			{
				float arg0 = (float)LuaDLL.luaL_checknumber(L, 1);
				UnityEngine.Transform arg1 = (UnityEngine.Transform)ToLua.CheckObject<UnityEngine.Transform>(L, 2);
				UnityEngine.Vector3 arg2 = ToLua.ToVector3(L, 3);
				float arg3 = (float)LuaDLL.luaL_checknumber(L, 4);
				LuaFramework.Tween.EaseType arg4 = (LuaFramework.Tween.EaseType)ToLua.CheckObject(L, 5, typeof(LuaFramework.Tween.EaseType));
				System.Action arg5 = (System.Action)ToLua.CheckDelegate<System.Action>(L, 6);
				LuaFramework.TweenEvent arg6 = (LuaFramework.TweenEvent)ToLua.CheckDelegate<LuaFramework.TweenEvent>(L, 7);
				bool arg7 = LuaDLL.luaL_checkboolean(L, 8);
				bool arg8 = LuaDLL.luaL_checkboolean(L, 9);
				bool arg9 = LuaDLL.luaL_checkboolean(L, 10);
				bool arg10 = LuaDLL.luaL_checkboolean(L, 11);
				LuaFramework.Tween.StartMove(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10);
				return 0;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to method: LuaFramework.Tween.StartMove");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int StopMove(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			UnityEngine.Transform arg0 = (UnityEngine.Transform)ToLua.CheckObject<UnityEngine.Transform>(L, 1);
			LuaFramework.Tween.StopMove(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int StartParabola(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 5 && TypeChecker.CheckTypes<float, float>(L, 4))
			{
				float arg0 = (float)LuaDLL.luaL_checknumber(L, 1);
				UnityEngine.Transform arg1 = (UnityEngine.Transform)ToLua.CheckObject<UnityEngine.Transform>(L, 2);
				UnityEngine.Vector3 arg2 = ToLua.ToVector3(L, 3);
				float arg3 = (float)LuaDLL.lua_tonumber(L, 4);
				float arg4 = (float)LuaDLL.lua_tonumber(L, 5);
				LuaFramework.Tween.StartParabola(arg0, arg1, arg2, arg3, arg4);
				return 0;
			}
			else if (count == 5 && TypeChecker.CheckTypes<UnityEngine.Vector3, float>(L, 4))
			{
				float arg0 = (float)LuaDLL.luaL_checknumber(L, 1);
				UnityEngine.Transform arg1 = (UnityEngine.Transform)ToLua.CheckObject<UnityEngine.Transform>(L, 2);
				UnityEngine.Vector3 arg2 = ToLua.ToVector3(L, 3);
				UnityEngine.Vector3 arg3 = ToLua.ToVector3(L, 4);
				float arg4 = (float)LuaDLL.lua_tonumber(L, 5);
				LuaFramework.Tween.StartParabola(arg0, arg1, arg2, arg3, arg4);
				return 0;
			}
			else if (count == 6 && TypeChecker.CheckTypes<float, float, bool>(L, 4))
			{
				float arg0 = (float)LuaDLL.luaL_checknumber(L, 1);
				UnityEngine.Transform arg1 = (UnityEngine.Transform)ToLua.CheckObject<UnityEngine.Transform>(L, 2);
				UnityEngine.Vector3 arg2 = ToLua.ToVector3(L, 3);
				float arg3 = (float)LuaDLL.lua_tonumber(L, 4);
				float arg4 = (float)LuaDLL.lua_tonumber(L, 5);
				bool arg5 = LuaDLL.lua_toboolean(L, 6);
				LuaFramework.Tween.StartParabola(arg0, arg1, arg2, arg3, arg4, arg5);
				return 0;
			}
			else if (count == 6 && TypeChecker.CheckTypes<UnityEngine.Vector3, float, bool>(L, 4))
			{
				float arg0 = (float)LuaDLL.luaL_checknumber(L, 1);
				UnityEngine.Transform arg1 = (UnityEngine.Transform)ToLua.CheckObject<UnityEngine.Transform>(L, 2);
				UnityEngine.Vector3 arg2 = ToLua.ToVector3(L, 3);
				UnityEngine.Vector3 arg3 = ToLua.ToVector3(L, 4);
				float arg4 = (float)LuaDLL.lua_tonumber(L, 5);
				bool arg5 = LuaDLL.lua_toboolean(L, 6);
				LuaFramework.Tween.StartParabola(arg0, arg1, arg2, arg3, arg4, arg5);
				return 0;
			}
			else if (count == 7 && TypeChecker.CheckTypes<float, float, bool, float>(L, 4))
			{
				float arg0 = (float)LuaDLL.luaL_checknumber(L, 1);
				UnityEngine.Transform arg1 = (UnityEngine.Transform)ToLua.CheckObject<UnityEngine.Transform>(L, 2);
				UnityEngine.Vector3 arg2 = ToLua.ToVector3(L, 3);
				float arg3 = (float)LuaDLL.lua_tonumber(L, 4);
				float arg4 = (float)LuaDLL.lua_tonumber(L, 5);
				bool arg5 = LuaDLL.lua_toboolean(L, 6);
				float arg6 = (float)LuaDLL.lua_tonumber(L, 7);
				LuaFramework.Tween.StartParabola(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
				return 0;
			}
			else if (count == 7 && TypeChecker.CheckTypes<UnityEngine.Vector3, float, bool, float>(L, 4))
			{
				float arg0 = (float)LuaDLL.luaL_checknumber(L, 1);
				UnityEngine.Transform arg1 = (UnityEngine.Transform)ToLua.CheckObject<UnityEngine.Transform>(L, 2);
				UnityEngine.Vector3 arg2 = ToLua.ToVector3(L, 3);
				UnityEngine.Vector3 arg3 = ToLua.ToVector3(L, 4);
				float arg4 = (float)LuaDLL.lua_tonumber(L, 5);
				bool arg5 = LuaDLL.lua_toboolean(L, 6);
				float arg6 = (float)LuaDLL.lua_tonumber(L, 7);
				LuaFramework.Tween.StartParabola(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
				return 0;
			}
			else if (count == 8 && TypeChecker.CheckTypes<float, float, bool, float, System.Action>(L, 4))
			{
				float arg0 = (float)LuaDLL.luaL_checknumber(L, 1);
				UnityEngine.Transform arg1 = (UnityEngine.Transform)ToLua.CheckObject<UnityEngine.Transform>(L, 2);
				UnityEngine.Vector3 arg2 = ToLua.ToVector3(L, 3);
				float arg3 = (float)LuaDLL.lua_tonumber(L, 4);
				float arg4 = (float)LuaDLL.lua_tonumber(L, 5);
				bool arg5 = LuaDLL.lua_toboolean(L, 6);
				float arg6 = (float)LuaDLL.lua_tonumber(L, 7);
				System.Action arg7 = (System.Action)ToLua.ToObject(L, 8);
				LuaFramework.Tween.StartParabola(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
				return 0;
			}
			else if (count == 8 && TypeChecker.CheckTypes<float, float, bool, float, LuaFramework.TweenEvent>(L, 4))
			{
				float arg0 = (float)LuaDLL.luaL_checknumber(L, 1);
				UnityEngine.Transform arg1 = (UnityEngine.Transform)ToLua.CheckObject<UnityEngine.Transform>(L, 2);
				UnityEngine.Vector3 arg2 = ToLua.ToVector3(L, 3);
				float arg3 = (float)LuaDLL.lua_tonumber(L, 4);
				float arg4 = (float)LuaDLL.lua_tonumber(L, 5);
				bool arg5 = LuaDLL.lua_toboolean(L, 6);
				float arg6 = (float)LuaDLL.lua_tonumber(L, 7);
				LuaFramework.TweenEvent arg7 = (LuaFramework.TweenEvent)ToLua.ToObject(L, 8);
				LuaFramework.Tween.StartParabola(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
				return 0;
			}
			else if (count == 8 && TypeChecker.CheckTypes<UnityEngine.Vector3, float, bool, float, System.Action>(L, 4))
			{
				float arg0 = (float)LuaDLL.luaL_checknumber(L, 1);
				UnityEngine.Transform arg1 = (UnityEngine.Transform)ToLua.CheckObject<UnityEngine.Transform>(L, 2);
				UnityEngine.Vector3 arg2 = ToLua.ToVector3(L, 3);
				UnityEngine.Vector3 arg3 = ToLua.ToVector3(L, 4);
				float arg4 = (float)LuaDLL.lua_tonumber(L, 5);
				bool arg5 = LuaDLL.lua_toboolean(L, 6);
				float arg6 = (float)LuaDLL.lua_tonumber(L, 7);
				System.Action arg7 = (System.Action)ToLua.ToObject(L, 8);
				LuaFramework.Tween.StartParabola(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
				return 0;
			}
			else if (count == 8 && TypeChecker.CheckTypes<UnityEngine.Vector3, float, bool, float, LuaFramework.TweenEvent>(L, 4))
			{
				float arg0 = (float)LuaDLL.luaL_checknumber(L, 1);
				UnityEngine.Transform arg1 = (UnityEngine.Transform)ToLua.CheckObject<UnityEngine.Transform>(L, 2);
				UnityEngine.Vector3 arg2 = ToLua.ToVector3(L, 3);
				UnityEngine.Vector3 arg3 = ToLua.ToVector3(L, 4);
				float arg4 = (float)LuaDLL.lua_tonumber(L, 5);
				bool arg5 = LuaDLL.lua_toboolean(L, 6);
				float arg6 = (float)LuaDLL.lua_tonumber(L, 7);
				LuaFramework.TweenEvent arg7 = (LuaFramework.TweenEvent)ToLua.ToObject(L, 8);
				LuaFramework.Tween.StartParabola(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
				return 0;
			}
			else if (count == 9 && TypeChecker.CheckTypes<float, float, bool, float, System.Action, System.Action>(L, 4))
			{
				float arg0 = (float)LuaDLL.luaL_checknumber(L, 1);
				UnityEngine.Transform arg1 = (UnityEngine.Transform)ToLua.CheckObject<UnityEngine.Transform>(L, 2);
				UnityEngine.Vector3 arg2 = ToLua.ToVector3(L, 3);
				float arg3 = (float)LuaDLL.lua_tonumber(L, 4);
				float arg4 = (float)LuaDLL.lua_tonumber(L, 5);
				bool arg5 = LuaDLL.lua_toboolean(L, 6);
				float arg6 = (float)LuaDLL.lua_tonumber(L, 7);
				System.Action arg7 = (System.Action)ToLua.ToObject(L, 8);
				System.Action arg8 = (System.Action)ToLua.ToObject(L, 9);
				LuaFramework.Tween.StartParabola(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
				return 0;
			}
			else if (count == 9 && TypeChecker.CheckTypes<float, float, bool, float, LuaFramework.TweenEvent, LuaFramework.TweenEvent>(L, 4))
			{
				float arg0 = (float)LuaDLL.luaL_checknumber(L, 1);
				UnityEngine.Transform arg1 = (UnityEngine.Transform)ToLua.CheckObject<UnityEngine.Transform>(L, 2);
				UnityEngine.Vector3 arg2 = ToLua.ToVector3(L, 3);
				float arg3 = (float)LuaDLL.lua_tonumber(L, 4);
				float arg4 = (float)LuaDLL.lua_tonumber(L, 5);
				bool arg5 = LuaDLL.lua_toboolean(L, 6);
				float arg6 = (float)LuaDLL.lua_tonumber(L, 7);
				LuaFramework.TweenEvent arg7 = (LuaFramework.TweenEvent)ToLua.ToObject(L, 8);
				LuaFramework.TweenEvent arg8 = (LuaFramework.TweenEvent)ToLua.ToObject(L, 9);
				LuaFramework.Tween.StartParabola(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
				return 0;
			}
			else if (count == 9 && TypeChecker.CheckTypes<UnityEngine.Vector3, float, bool, float, System.Action, System.Action>(L, 4))
			{
				float arg0 = (float)LuaDLL.luaL_checknumber(L, 1);
				UnityEngine.Transform arg1 = (UnityEngine.Transform)ToLua.CheckObject<UnityEngine.Transform>(L, 2);
				UnityEngine.Vector3 arg2 = ToLua.ToVector3(L, 3);
				UnityEngine.Vector3 arg3 = ToLua.ToVector3(L, 4);
				float arg4 = (float)LuaDLL.lua_tonumber(L, 5);
				bool arg5 = LuaDLL.lua_toboolean(L, 6);
				float arg6 = (float)LuaDLL.lua_tonumber(L, 7);
				System.Action arg7 = (System.Action)ToLua.ToObject(L, 8);
				System.Action arg8 = (System.Action)ToLua.ToObject(L, 9);
				LuaFramework.Tween.StartParabola(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
				return 0;
			}
			else if (count == 9 && TypeChecker.CheckTypes<UnityEngine.Vector3, float, bool, float, LuaFramework.TweenEvent, LuaFramework.TweenEvent>(L, 4))
			{
				float arg0 = (float)LuaDLL.luaL_checknumber(L, 1);
				UnityEngine.Transform arg1 = (UnityEngine.Transform)ToLua.CheckObject<UnityEngine.Transform>(L, 2);
				UnityEngine.Vector3 arg2 = ToLua.ToVector3(L, 3);
				UnityEngine.Vector3 arg3 = ToLua.ToVector3(L, 4);
				float arg4 = (float)LuaDLL.lua_tonumber(L, 5);
				bool arg5 = LuaDLL.lua_toboolean(L, 6);
				float arg6 = (float)LuaDLL.lua_tonumber(L, 7);
				LuaFramework.TweenEvent arg7 = (LuaFramework.TweenEvent)ToLua.ToObject(L, 8);
				LuaFramework.TweenEvent arg8 = (LuaFramework.TweenEvent)ToLua.ToObject(L, 9);
				LuaFramework.Tween.StartParabola(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
				return 0;
			}
			else if (count == 11 && TypeChecker.CheckTypes<float, float, bool, float, System.Action, LuaFramework.TweenEvent, System.Action, LuaFramework.TweenEvent>(L, 4))
			{
				float arg0 = (float)LuaDLL.luaL_checknumber(L, 1);
				UnityEngine.Transform arg1 = (UnityEngine.Transform)ToLua.CheckObject<UnityEngine.Transform>(L, 2);
				UnityEngine.Vector3 arg2 = ToLua.ToVector3(L, 3);
				float arg3 = (float)LuaDLL.lua_tonumber(L, 4);
				float arg4 = (float)LuaDLL.lua_tonumber(L, 5);
				bool arg5 = LuaDLL.lua_toboolean(L, 6);
				float arg6 = (float)LuaDLL.lua_tonumber(L, 7);
				System.Action arg7 = (System.Action)ToLua.ToObject(L, 8);
				LuaFramework.TweenEvent arg8 = (LuaFramework.TweenEvent)ToLua.ToObject(L, 9);
				System.Action arg9 = (System.Action)ToLua.ToObject(L, 10);
				LuaFramework.TweenEvent arg10 = (LuaFramework.TweenEvent)ToLua.ToObject(L, 11);
				LuaFramework.Tween.StartParabola(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10);
				return 0;
			}
			else if (count == 11 && TypeChecker.CheckTypes<UnityEngine.Vector3, float, bool, float, System.Action, LuaFramework.TweenEvent, System.Action, LuaFramework.TweenEvent>(L, 4))
			{
				float arg0 = (float)LuaDLL.luaL_checknumber(L, 1);
				UnityEngine.Transform arg1 = (UnityEngine.Transform)ToLua.CheckObject<UnityEngine.Transform>(L, 2);
				UnityEngine.Vector3 arg2 = ToLua.ToVector3(L, 3);
				UnityEngine.Vector3 arg3 = ToLua.ToVector3(L, 4);
				float arg4 = (float)LuaDLL.lua_tonumber(L, 5);
				bool arg5 = LuaDLL.lua_toboolean(L, 6);
				float arg6 = (float)LuaDLL.lua_tonumber(L, 7);
				System.Action arg7 = (System.Action)ToLua.ToObject(L, 8);
				LuaFramework.TweenEvent arg8 = (LuaFramework.TweenEvent)ToLua.ToObject(L, 9);
				System.Action arg9 = (System.Action)ToLua.ToObject(L, 10);
				LuaFramework.TweenEvent arg10 = (LuaFramework.TweenEvent)ToLua.ToObject(L, 11);
				LuaFramework.Tween.StartParabola(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10);
				return 0;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to method: LuaFramework.Tween.StartParabola");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int StopParabola(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			UnityEngine.Transform arg0 = (UnityEngine.Transform)ToLua.CheckObject<UnityEngine.Transform>(L, 1);
			LuaFramework.Tween.StopParabola(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetScale(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.Transform arg0 = (UnityEngine.Transform)ToLua.CheckObject<UnityEngine.Transform>(L, 1);
			UnityEngine.Vector3 arg1 = ToLua.ToVector3(L, 2);
			LuaFramework.Tween.SetScale(arg0, arg1);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int StartScale(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 5)
			{
				float arg0 = (float)LuaDLL.luaL_checknumber(L, 1);
				UnityEngine.Transform arg1 = (UnityEngine.Transform)ToLua.CheckObject<UnityEngine.Transform>(L, 2);
				UnityEngine.Vector3 arg2 = ToLua.ToVector3(L, 3);
				float arg3 = (float)LuaDLL.luaL_checknumber(L, 4);
				LuaFramework.Tween.EaseType arg4 = (LuaFramework.Tween.EaseType)ToLua.CheckObject(L, 5, typeof(LuaFramework.Tween.EaseType));
				LuaFramework.Tween.StartScale(arg0, arg1, arg2, arg3, arg4);
				return 0;
			}
			else if (count == 6 && TypeChecker.CheckTypes<System.Action>(L, 6))
			{
				float arg0 = (float)LuaDLL.luaL_checknumber(L, 1);
				UnityEngine.Transform arg1 = (UnityEngine.Transform)ToLua.CheckObject<UnityEngine.Transform>(L, 2);
				UnityEngine.Vector3 arg2 = ToLua.ToVector3(L, 3);
				float arg3 = (float)LuaDLL.luaL_checknumber(L, 4);
				LuaFramework.Tween.EaseType arg4 = (LuaFramework.Tween.EaseType)ToLua.CheckObject(L, 5, typeof(LuaFramework.Tween.EaseType));
				System.Action arg5 = (System.Action)ToLua.ToObject(L, 6);
				LuaFramework.Tween.StartScale(arg0, arg1, arg2, arg3, arg4, arg5);
				return 0;
			}
			else if (count == 6 && TypeChecker.CheckTypes<LuaFramework.TweenEvent>(L, 6))
			{
				float arg0 = (float)LuaDLL.luaL_checknumber(L, 1);
				UnityEngine.Transform arg1 = (UnityEngine.Transform)ToLua.CheckObject<UnityEngine.Transform>(L, 2);
				UnityEngine.Vector3 arg2 = ToLua.ToVector3(L, 3);
				float arg3 = (float)LuaDLL.luaL_checknumber(L, 4);
				LuaFramework.Tween.EaseType arg4 = (LuaFramework.Tween.EaseType)ToLua.CheckObject(L, 5, typeof(LuaFramework.Tween.EaseType));
				LuaFramework.TweenEvent arg5 = (LuaFramework.TweenEvent)ToLua.ToObject(L, 6);
				LuaFramework.Tween.StartScale(arg0, arg1, arg2, arg3, arg4, arg5);
				return 0;
			}
			else if (count == 7)
			{
				float arg0 = (float)LuaDLL.luaL_checknumber(L, 1);
				UnityEngine.Transform arg1 = (UnityEngine.Transform)ToLua.CheckObject<UnityEngine.Transform>(L, 2);
				UnityEngine.Vector3 arg2 = ToLua.ToVector3(L, 3);
				float arg3 = (float)LuaDLL.luaL_checknumber(L, 4);
				LuaFramework.Tween.EaseType arg4 = (LuaFramework.Tween.EaseType)ToLua.CheckObject(L, 5, typeof(LuaFramework.Tween.EaseType));
				System.Action arg5 = (System.Action)ToLua.CheckDelegate<System.Action>(L, 6);
				LuaFramework.TweenEvent arg6 = (LuaFramework.TweenEvent)ToLua.CheckDelegate<LuaFramework.TweenEvent>(L, 7);
				LuaFramework.Tween.StartScale(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
				return 0;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to method: LuaFramework.Tween.StartScale");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int StopScale(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			UnityEngine.Transform arg0 = (UnityEngine.Transform)ToLua.CheckObject<UnityEngine.Transform>(L, 1);
			LuaFramework.Tween.StopScale(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetUISize(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.Transform arg0 = (UnityEngine.Transform)ToLua.CheckObject<UnityEngine.Transform>(L, 1);
			UnityEngine.Vector2 arg1 = ToLua.ToVector2(L, 2);
			LuaFramework.Tween.SetUISize(arg0, arg1);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int StartUISize(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 5)
			{
				float arg0 = (float)LuaDLL.luaL_checknumber(L, 1);
				UnityEngine.Transform arg1 = (UnityEngine.Transform)ToLua.CheckObject<UnityEngine.Transform>(L, 2);
				UnityEngine.Vector2 arg2 = ToLua.ToVector2(L, 3);
				float arg3 = (float)LuaDLL.luaL_checknumber(L, 4);
				LuaFramework.Tween.EaseType arg4 = (LuaFramework.Tween.EaseType)ToLua.CheckObject(L, 5, typeof(LuaFramework.Tween.EaseType));
				LuaFramework.Tween.StartUISize(arg0, arg1, arg2, arg3, arg4);
				return 0;
			}
			else if (count == 6 && TypeChecker.CheckTypes<System.Action>(L, 6))
			{
				float arg0 = (float)LuaDLL.luaL_checknumber(L, 1);
				UnityEngine.Transform arg1 = (UnityEngine.Transform)ToLua.CheckObject<UnityEngine.Transform>(L, 2);
				UnityEngine.Vector2 arg2 = ToLua.ToVector2(L, 3);
				float arg3 = (float)LuaDLL.luaL_checknumber(L, 4);
				LuaFramework.Tween.EaseType arg4 = (LuaFramework.Tween.EaseType)ToLua.CheckObject(L, 5, typeof(LuaFramework.Tween.EaseType));
				System.Action arg5 = (System.Action)ToLua.ToObject(L, 6);
				LuaFramework.Tween.StartUISize(arg0, arg1, arg2, arg3, arg4, arg5);
				return 0;
			}
			else if (count == 6 && TypeChecker.CheckTypes<LuaFramework.TweenEvent>(L, 6))
			{
				float arg0 = (float)LuaDLL.luaL_checknumber(L, 1);
				UnityEngine.Transform arg1 = (UnityEngine.Transform)ToLua.CheckObject<UnityEngine.Transform>(L, 2);
				UnityEngine.Vector2 arg2 = ToLua.ToVector2(L, 3);
				float arg3 = (float)LuaDLL.luaL_checknumber(L, 4);
				LuaFramework.Tween.EaseType arg4 = (LuaFramework.Tween.EaseType)ToLua.CheckObject(L, 5, typeof(LuaFramework.Tween.EaseType));
				LuaFramework.TweenEvent arg5 = (LuaFramework.TweenEvent)ToLua.ToObject(L, 6);
				LuaFramework.Tween.StartUISize(arg0, arg1, arg2, arg3, arg4, arg5);
				return 0;
			}
			else if (count == 7)
			{
				float arg0 = (float)LuaDLL.luaL_checknumber(L, 1);
				UnityEngine.Transform arg1 = (UnityEngine.Transform)ToLua.CheckObject<UnityEngine.Transform>(L, 2);
				UnityEngine.Vector2 arg2 = ToLua.ToVector2(L, 3);
				float arg3 = (float)LuaDLL.luaL_checknumber(L, 4);
				LuaFramework.Tween.EaseType arg4 = (LuaFramework.Tween.EaseType)ToLua.CheckObject(L, 5, typeof(LuaFramework.Tween.EaseType));
				System.Action arg5 = (System.Action)ToLua.CheckDelegate<System.Action>(L, 6);
				LuaFramework.TweenEvent arg6 = (LuaFramework.TweenEvent)ToLua.CheckDelegate<LuaFramework.TweenEvent>(L, 7);
				LuaFramework.Tween.StartUISize(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
				return 0;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to method: LuaFramework.Tween.StartUISize");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int StopUISize(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			UnityEngine.Transform arg0 = (UnityEngine.Transform)ToLua.CheckObject<UnityEngine.Transform>(L, 1);
			LuaFramework.Tween.StopUISize(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetAlpha(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 2)
			{
				UnityEngine.Transform arg0 = (UnityEngine.Transform)ToLua.CheckObject<UnityEngine.Transform>(L, 1);
				float arg1 = (float)LuaDLL.luaL_checknumber(L, 2);
				LuaFramework.Tween.SetAlpha(arg0, arg1);
				return 0;
			}
			else if (count == 3)
			{
				UnityEngine.Transform arg0 = (UnityEngine.Transform)ToLua.CheckObject<UnityEngine.Transform>(L, 1);
				float arg1 = (float)LuaDLL.luaL_checknumber(L, 2);
				bool arg2 = LuaDLL.luaL_checkboolean(L, 3);
				LuaFramework.Tween.SetAlpha(arg0, arg1, arg2);
				return 0;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to method: LuaFramework.Tween.SetAlpha");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int StartAlpha(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 5)
			{
				float arg0 = (float)LuaDLL.luaL_checknumber(L, 1);
				UnityEngine.Transform arg1 = (UnityEngine.Transform)ToLua.CheckObject<UnityEngine.Transform>(L, 2);
				float arg2 = (float)LuaDLL.luaL_checknumber(L, 3);
				float arg3 = (float)LuaDLL.luaL_checknumber(L, 4);
				LuaFramework.Tween.EaseType arg4 = (LuaFramework.Tween.EaseType)ToLua.CheckObject(L, 5, typeof(LuaFramework.Tween.EaseType));
				LuaFramework.Tween.StartAlpha(arg0, arg1, arg2, arg3, arg4);
				return 0;
			}
			else if (count == 6)
			{
				float arg0 = (float)LuaDLL.luaL_checknumber(L, 1);
				UnityEngine.Transform arg1 = (UnityEngine.Transform)ToLua.CheckObject<UnityEngine.Transform>(L, 2);
				float arg2 = (float)LuaDLL.luaL_checknumber(L, 3);
				float arg3 = (float)LuaDLL.luaL_checknumber(L, 4);
				LuaFramework.Tween.EaseType arg4 = (LuaFramework.Tween.EaseType)ToLua.CheckObject(L, 5, typeof(LuaFramework.Tween.EaseType));
				System.Action arg5 = (System.Action)ToLua.CheckDelegate<System.Action>(L, 6);
				LuaFramework.Tween.StartAlpha(arg0, arg1, arg2, arg3, arg4, arg5);
				return 0;
			}
			else if (count == 7)
			{
				float arg0 = (float)LuaDLL.luaL_checknumber(L, 1);
				UnityEngine.Transform arg1 = (UnityEngine.Transform)ToLua.CheckObject<UnityEngine.Transform>(L, 2);
				float arg2 = (float)LuaDLL.luaL_checknumber(L, 3);
				float arg3 = (float)LuaDLL.luaL_checknumber(L, 4);
				LuaFramework.Tween.EaseType arg4 = (LuaFramework.Tween.EaseType)ToLua.CheckObject(L, 5, typeof(LuaFramework.Tween.EaseType));
				System.Action arg5 = (System.Action)ToLua.CheckDelegate<System.Action>(L, 6);
				LuaFramework.TweenEvent arg6 = (LuaFramework.TweenEvent)ToLua.CheckDelegate<LuaFramework.TweenEvent>(L, 7);
				LuaFramework.Tween.StartAlpha(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
				return 0;
			}
			else if (count == 8)
			{
				float arg0 = (float)LuaDLL.luaL_checknumber(L, 1);
				UnityEngine.Transform arg1 = (UnityEngine.Transform)ToLua.CheckObject<UnityEngine.Transform>(L, 2);
				float arg2 = (float)LuaDLL.luaL_checknumber(L, 3);
				float arg3 = (float)LuaDLL.luaL_checknumber(L, 4);
				LuaFramework.Tween.EaseType arg4 = (LuaFramework.Tween.EaseType)ToLua.CheckObject(L, 5, typeof(LuaFramework.Tween.EaseType));
				System.Action arg5 = (System.Action)ToLua.CheckDelegate<System.Action>(L, 6);
				LuaFramework.TweenEvent arg6 = (LuaFramework.TweenEvent)ToLua.CheckDelegate<LuaFramework.TweenEvent>(L, 7);
				bool arg7 = LuaDLL.luaL_checkboolean(L, 8);
				LuaFramework.Tween.StartAlpha(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
				return 0;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to method: LuaFramework.Tween.StartAlpha");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int StopAlpha(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			UnityEngine.Transform arg0 = (UnityEngine.Transform)ToLua.CheckObject<UnityEngine.Transform>(L, 1);
			LuaFramework.Tween.StopAlpha(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int StartShake(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 4)
			{
				float arg0 = (float)LuaDLL.luaL_checknumber(L, 1);
				UnityEngine.Transform arg1 = (UnityEngine.Transform)ToLua.CheckObject<UnityEngine.Transform>(L, 2);
				float arg2 = (float)LuaDLL.luaL_checknumber(L, 3);
				float arg3 = (float)LuaDLL.luaL_checknumber(L, 4);
				LuaFramework.Tween.StartShake(arg0, arg1, arg2, arg3);
				return 0;
			}
			else if (count == 5 && TypeChecker.CheckTypes<float>(L, 5))
			{
				float arg0 = (float)LuaDLL.luaL_checknumber(L, 1);
				UnityEngine.Transform arg1 = (UnityEngine.Transform)ToLua.CheckObject<UnityEngine.Transform>(L, 2);
				float arg2 = (float)LuaDLL.luaL_checknumber(L, 3);
				float arg3 = (float)LuaDLL.luaL_checknumber(L, 4);
				float arg4 = (float)LuaDLL.lua_tonumber(L, 5);
				LuaFramework.Tween.StartShake(arg0, arg1, arg2, arg3, arg4);
				return 0;
			}
			else if (count == 5 && TypeChecker.CheckTypes<System.Action>(L, 5))
			{
				float arg0 = (float)LuaDLL.luaL_checknumber(L, 1);
				UnityEngine.Transform arg1 = (UnityEngine.Transform)ToLua.CheckObject<UnityEngine.Transform>(L, 2);
				float arg2 = (float)LuaDLL.luaL_checknumber(L, 3);
				float arg3 = (float)LuaDLL.luaL_checknumber(L, 4);
				System.Action arg4 = (System.Action)ToLua.ToObject(L, 5);
				LuaFramework.Tween.StartShake(arg0, arg1, arg2, arg3, arg4);
				return 0;
			}
			else if (count == 6 && TypeChecker.CheckTypes<System.Action>(L, 6))
			{
				float arg0 = (float)LuaDLL.luaL_checknumber(L, 1);
				UnityEngine.Transform arg1 = (UnityEngine.Transform)ToLua.CheckObject<UnityEngine.Transform>(L, 2);
				float arg2 = (float)LuaDLL.luaL_checknumber(L, 3);
				float arg3 = (float)LuaDLL.luaL_checknumber(L, 4);
				float arg4 = (float)LuaDLL.luaL_checknumber(L, 5);
				System.Action arg5 = (System.Action)ToLua.ToObject(L, 6);
				LuaFramework.Tween.StartShake(arg0, arg1, arg2, arg3, arg4, arg5);
				return 0;
			}
			else if (count == 6 && TypeChecker.CheckTypes<LuaFramework.TweenEvent>(L, 6))
			{
				float arg0 = (float)LuaDLL.luaL_checknumber(L, 1);
				UnityEngine.Transform arg1 = (UnityEngine.Transform)ToLua.CheckObject<UnityEngine.Transform>(L, 2);
				float arg2 = (float)LuaDLL.luaL_checknumber(L, 3);
				float arg3 = (float)LuaDLL.luaL_checknumber(L, 4);
				float arg4 = (float)LuaDLL.luaL_checknumber(L, 5);
				LuaFramework.TweenEvent arg5 = (LuaFramework.TweenEvent)ToLua.ToObject(L, 6);
				LuaFramework.Tween.StartShake(arg0, arg1, arg2, arg3, arg4, arg5);
				return 0;
			}
			else if (count == 7)
			{
				float arg0 = (float)LuaDLL.luaL_checknumber(L, 1);
				UnityEngine.Transform arg1 = (UnityEngine.Transform)ToLua.CheckObject<UnityEngine.Transform>(L, 2);
				float arg2 = (float)LuaDLL.luaL_checknumber(L, 3);
				float arg3 = (float)LuaDLL.luaL_checknumber(L, 4);
				float arg4 = (float)LuaDLL.luaL_checknumber(L, 5);
				System.Action arg5 = (System.Action)ToLua.CheckDelegate<System.Action>(L, 6);
				LuaFramework.TweenEvent arg6 = (LuaFramework.TweenEvent)ToLua.CheckDelegate<LuaFramework.TweenEvent>(L, 7);
				LuaFramework.Tween.StartShake(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
				return 0;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to method: LuaFramework.Tween.StartShake");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int StopShake(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			UnityEngine.Transform arg0 = (UnityEngine.Transform)ToLua.CheckObject<UnityEngine.Transform>(L, 1);
			LuaFramework.Tween.StopShake(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int StartSwing(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 6)
			{
				float arg0 = (float)LuaDLL.luaL_checknumber(L, 1);
				UnityEngine.Transform arg1 = (UnityEngine.Transform)ToLua.CheckObject<UnityEngine.Transform>(L, 2);
				float arg2 = (float)LuaDLL.luaL_checknumber(L, 3);
				float arg3 = (float)LuaDLL.luaL_checknumber(L, 4);
				float arg4 = (float)LuaDLL.luaL_checknumber(L, 5);
				bool arg5 = LuaDLL.luaL_checkboolean(L, 6);
				LuaFramework.Tween.StartSwing(arg0, arg1, arg2, arg3, arg4, arg5);
				return 0;
			}
			else if (count == 7 && TypeChecker.CheckTypes<System.Action>(L, 7))
			{
				float arg0 = (float)LuaDLL.luaL_checknumber(L, 1);
				UnityEngine.Transform arg1 = (UnityEngine.Transform)ToLua.CheckObject<UnityEngine.Transform>(L, 2);
				float arg2 = (float)LuaDLL.luaL_checknumber(L, 3);
				float arg3 = (float)LuaDLL.luaL_checknumber(L, 4);
				float arg4 = (float)LuaDLL.luaL_checknumber(L, 5);
				bool arg5 = LuaDLL.luaL_checkboolean(L, 6);
				System.Action arg6 = (System.Action)ToLua.ToObject(L, 7);
				LuaFramework.Tween.StartSwing(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
				return 0;
			}
			else if (count == 7 && TypeChecker.CheckTypes<LuaFramework.TweenEvent>(L, 7))
			{
				float arg0 = (float)LuaDLL.luaL_checknumber(L, 1);
				UnityEngine.Transform arg1 = (UnityEngine.Transform)ToLua.CheckObject<UnityEngine.Transform>(L, 2);
				float arg2 = (float)LuaDLL.luaL_checknumber(L, 3);
				float arg3 = (float)LuaDLL.luaL_checknumber(L, 4);
				float arg4 = (float)LuaDLL.luaL_checknumber(L, 5);
				bool arg5 = LuaDLL.luaL_checkboolean(L, 6);
				LuaFramework.TweenEvent arg6 = (LuaFramework.TweenEvent)ToLua.ToObject(L, 7);
				LuaFramework.Tween.StartSwing(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
				return 0;
			}
			else if (count == 8)
			{
				float arg0 = (float)LuaDLL.luaL_checknumber(L, 1);
				UnityEngine.Transform arg1 = (UnityEngine.Transform)ToLua.CheckObject<UnityEngine.Transform>(L, 2);
				float arg2 = (float)LuaDLL.luaL_checknumber(L, 3);
				float arg3 = (float)LuaDLL.luaL_checknumber(L, 4);
				float arg4 = (float)LuaDLL.luaL_checknumber(L, 5);
				bool arg5 = LuaDLL.luaL_checkboolean(L, 6);
				System.Action arg6 = (System.Action)ToLua.CheckDelegate<System.Action>(L, 7);
				LuaFramework.TweenEvent arg7 = (LuaFramework.TweenEvent)ToLua.CheckDelegate<LuaFramework.TweenEvent>(L, 8);
				LuaFramework.Tween.StartSwing(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
				return 0;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to method: LuaFramework.Tween.StartSwing");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int StopSwing(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			UnityEngine.Transform arg0 = (UnityEngine.Transform)ToLua.CheckObject<UnityEngine.Transform>(L, 1);
			LuaFramework.Tween.StopSwing(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int StartValue(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 6)
			{
				float arg0 = (float)LuaDLL.luaL_checknumber(L, 1);
				float arg1 = (float)LuaDLL.luaL_checknumber(L, 2);
				float arg2 = (float)LuaDLL.luaL_checknumber(L, 3);
				float arg3 = (float)LuaDLL.luaL_checknumber(L, 4);
				LuaFramework.Tween.EaseType arg4 = (LuaFramework.Tween.EaseType)ToLua.CheckObject(L, 5, typeof(LuaFramework.Tween.EaseType));
				System.Action<float> arg5 = (System.Action<float>)ToLua.CheckDelegate<System.Action<float>>(L, 6);
				LuaFramework.ValueUpdate o = LuaFramework.Tween.StartValue(arg0, arg1, arg2, arg3, arg4, arg5);
				ToLua.Push(L, o);
				return 1;
			}
			else if (count == 7)
			{
				float arg0 = (float)LuaDLL.luaL_checknumber(L, 1);
				float arg1 = (float)LuaDLL.luaL_checknumber(L, 2);
				float arg2 = (float)LuaDLL.luaL_checknumber(L, 3);
				float arg3 = (float)LuaDLL.luaL_checknumber(L, 4);
				LuaFramework.Tween.EaseType arg4 = (LuaFramework.Tween.EaseType)ToLua.CheckObject(L, 5, typeof(LuaFramework.Tween.EaseType));
				System.Action<float> arg5 = (System.Action<float>)ToLua.CheckDelegate<System.Action<float>>(L, 6);
				System.Action arg6 = (System.Action)ToLua.CheckDelegate<System.Action>(L, 7);
				LuaFramework.ValueUpdate o = LuaFramework.Tween.StartValue(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
				ToLua.Push(L, o);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to method: LuaFramework.Tween.StartValue");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Linear(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 5);
			LuaFramework.Tween obj = (LuaFramework.Tween)ToLua.CheckObject<LuaFramework.Tween>(L, 1);
			double arg0 = (double)LuaDLL.luaL_checknumber(L, 2);
			double arg1 = (double)LuaDLL.luaL_checknumber(L, 3);
			double arg2 = (double)LuaDLL.luaL_checknumber(L, 4);
			double arg3 = (double)LuaDLL.luaL_checknumber(L, 5);
			double o = obj.Linear(arg0, arg1, arg2, arg3);
			LuaDLL.lua_pushnumber(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Ease(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 5);
			LuaFramework.Tween obj = (LuaFramework.Tween)ToLua.CheckObject<LuaFramework.Tween>(L, 1);
			double arg0 = (double)LuaDLL.luaL_checknumber(L, 2);
			double arg1 = (double)LuaDLL.luaL_checknumber(L, 3);
			double arg2 = (double)LuaDLL.luaL_checknumber(L, 4);
			double arg3 = (double)LuaDLL.luaL_checknumber(L, 5);
			double o = obj.Ease(arg0, arg1, arg2, arg3);
			LuaDLL.lua_pushnumber(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

