//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class LuaFramework_Tween_EaseTypeWrap
{
	public static void Register(LuaState L)
	{
		L.BeginEnum(typeof(LuaFramework.Tween.EaseType));
		L.RegVar("Linear", get_Linear, null);
		L.RegVar("ExpoIn", get_ExpoIn, null);
		L.RegVar("ExpoOut", get_ExpoOut, null);
		L.RegVar("ExpoInOut", get_ExpoInOut, null);
		L.RegVar("SineIn", get_SineIn, null);
		L.RegVar("SineOut", get_SineOut, null);
		L.RegVar("SineInOut", get_SineInOut, null);
		L.RegVar("ElasticIn", get_ElasticIn, null);
		L.RegVar("ElasticOut", get_ElasticOut, null);
		L.RegVar("ElasticInOut", get_ElasticInOut, null);
		L.RegVar("BackIn", get_BackIn, null);
		L.RegVar("BackOut", get_BackOut, null);
		L.RegVar("BackInOut", get_BackInOut, null);
		L.RegVar("BounceIn", get_BounceIn, null);
		L.RegVar("BounceOut", get_BounceOut, null);
		L.RegVar("BounceInOut", get_BounceInOut, null);
		L.RegFunction("IntToEnum", IntToEnum);
		L.EndEnum();
		TypeTraits<LuaFramework.Tween.EaseType>.Check = CheckType;
		StackTraits<LuaFramework.Tween.EaseType>.Push = Push;
	}

	static void Push(IntPtr L, LuaFramework.Tween.EaseType arg)
	{
		ToLua.Push(L, arg);
	}

	static bool CheckType(IntPtr L, int pos)
	{
		return TypeChecker.CheckEnumType(typeof(LuaFramework.Tween.EaseType), L, pos);
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Linear(IntPtr L)
	{
		ToLua.Push(L, LuaFramework.Tween.EaseType.Linear);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_ExpoIn(IntPtr L)
	{
		ToLua.Push(L, LuaFramework.Tween.EaseType.ExpoIn);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_ExpoOut(IntPtr L)
	{
		ToLua.Push(L, LuaFramework.Tween.EaseType.ExpoOut);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_ExpoInOut(IntPtr L)
	{
		ToLua.Push(L, LuaFramework.Tween.EaseType.ExpoInOut);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_SineIn(IntPtr L)
	{
		ToLua.Push(L, LuaFramework.Tween.EaseType.SineIn);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_SineOut(IntPtr L)
	{
		ToLua.Push(L, LuaFramework.Tween.EaseType.SineOut);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_SineInOut(IntPtr L)
	{
		ToLua.Push(L, LuaFramework.Tween.EaseType.SineInOut);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_ElasticIn(IntPtr L)
	{
		ToLua.Push(L, LuaFramework.Tween.EaseType.ElasticIn);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_ElasticOut(IntPtr L)
	{
		ToLua.Push(L, LuaFramework.Tween.EaseType.ElasticOut);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_ElasticInOut(IntPtr L)
	{
		ToLua.Push(L, LuaFramework.Tween.EaseType.ElasticInOut);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_BackIn(IntPtr L)
	{
		ToLua.Push(L, LuaFramework.Tween.EaseType.BackIn);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_BackOut(IntPtr L)
	{
		ToLua.Push(L, LuaFramework.Tween.EaseType.BackOut);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_BackInOut(IntPtr L)
	{
		ToLua.Push(L, LuaFramework.Tween.EaseType.BackInOut);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_BounceIn(IntPtr L)
	{
		ToLua.Push(L, LuaFramework.Tween.EaseType.BounceIn);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_BounceOut(IntPtr L)
	{
		ToLua.Push(L, LuaFramework.Tween.EaseType.BounceOut);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_BounceInOut(IntPtr L)
	{
		ToLua.Push(L, LuaFramework.Tween.EaseType.BounceInOut);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int IntToEnum(IntPtr L)
	{
		int arg0 = (int)LuaDLL.lua_tonumber(L, 1);
		LuaFramework.Tween.EaseType o = (LuaFramework.Tween.EaseType)arg0;
		ToLua.Push(L, o);
		return 1;
	}
}

